### ISSUE TITLE
add historische karten to base maps

### ISSUE THREAD

**Issue by robarto** [giatschool/webgis.nrw#63]
https://www.bezreg-koeln.nrw.de/brk_internet/geobasis/webdienste/geodatendienste/index.html

add the followingg WMS: 

    1801 – 1828 Tranchot: https://www.wms.nrw.de/geobasis/wms_nw_tranchot
    1836 – 1850 Uraufnahme: https://www.wms.nrw.de/geobasis/wms_nw_uraufnahme
    1881 – 1883 Fürstenthum Lippe: https://www.wms.nrw.de/geobasis/wms_nw_lippe
    1891 – 1912 Neuaufnahme: https://www.wms.nrw.de/geobasis/wms_nw_neuaufnahme
TK25 1936-1945: https://www.wms.nrw.de/geobasis/wms_nw_tk25_1936-1945
DGK5 – historisch: https://www.wms.nrw.de/geobasis/wms_nw_dgk5

**Comment by felixerdy** [comment]
- [x] Tranchot 
- [x] Uraufnahme
- [ ] Fürstenthum Lippe (leider kein layer sichtbar)
- [x] Neuaufnahme
- [x] TK25 1936-1945
- [x] DGK5 – historisch (scheint nicht so historisch)

**Comment by robarto** [comment]
Bitte noch die Anordnung anpassen: 

DGK5 hoch zu den Amtlichen Karten. Button "DGK5", Tooltip "DGK5 - historisch"

Die anderen jeweils nur mit den Jahreszahlen als Buttons ggf. etwasenger, dass sie in eine Zeile passen, wie die anderen drei. Und die Gesamtbezeichnungen dann auch in den Tooltip.
